modLoader="javafml"
loaderVersion="[1,)"
license="MIT"
issueTrackerURL="https://github.com/firstdarkdev/sdlink/issues"

[[mods]]
    modId="${mod_id}"
    version="${version}"
    displayName="${mod_name}"
    logoFile="sdlink_logo.png"
    authors="${mod_author}"
    description='''A simple Minecraft to Discord Chat bot with Whitelisting'''
    displayTest = "IGNORE_SERVER_VERSION"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[20.4,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.4,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="craterlib"
    mandatory=true
    versionRange="[2.1.0,)"
    ordering="AFTER"
    side="SERVER"